[package]
name = "new_interpreter"
version = "0.1.0"
authors = ["Arturo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
indexmap = "2.0.0"
dyn-clone = "1.0.9"
itertools = "0.10.5"
ahash = "0.8.3"
bstr = "1.1.0"
peg = "0.8.1"
mimalloc-rust = "0.2.0"
derive_more = "0.99.17"
paste = "1.0.12"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false

[profile.bench]
debug = true
lto = true
codegen-units = 1

[profile.release]
#strip = true
#debug = true
lto = true
codegen-units = 1
panic = "abort"
