[package]
name = "new_interpreter"
version = "0.1.0"
authors = ["Arturo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
indexmap = "1.9.1"
unicode-segmentation = "1.9.0"
dyn-clone = "1.0.5"
regex = "1.5.5"
itertools = "0.10.3"
ahash = "0.8.0"

[dev-dependencies]
criterion = "0.3.5"


[[bench]]
name = "my_benchmark"
harness = false

[profile.bench]
debug = true
lto = true
codegen-units = 1

[profile.release]
#strip = true
debug = true
lto = true
codegen-units = 1
panic = "abort"
